### ISSUE TITLE
How to display the article list on the index page

### ISSUE THREAD

**Issue by lnzx** [12bitvn/12bit.vn#16]
hi,
good project,
but, I have a problem, 
How to display the article list on the index page? 
![list](https://user-images.githubusercontent.com/1515417/66376090-67ce5680-e9e1-11e9-810c-49c6e12a1360.png)

(Làm thế nào để hiển thị danh sách bài viết trên trang chỉ mục?)
thanks.

**Comment by tatthien** [comment]
Hi @lnzx 
Thanks for taking your time on this project. I'm not sure what makes this issue.
Could you try making a simple hack by changing the `baseURL` in `config.yaml` to something else? It worked for me.

**Comment by lnzx** [comment]
hi,
Thank you for your help. The problem has been solved.
I did not modify `config.yaml`.
Just deleted this code.
`index.html`
![index](https://user-images.githubusercontent.com/1515417/66446553-9ef24580-ea7d-11e9-93a5-525f14346d6b.png)
it worked. 
![article_list](https://user-images.githubusercontent.com/1515417/66446639-fbedfb80-ea7d-11e9-9d17-728abda926aa.png)
I don't know what's the reason.
