### ISSUE TITLE
can't give argument to non-function $.Page.Scratch.Get "include_caniuse"

### ISSUE THREAD

**Issue by lnzx** [12bitvn/12bit.vn#27]
hi,
My hugo version:
`Hugo Static Site Generator v0.72.0/extended windows/amd64`

Error message：
` error calling partial: "D:\var\git\12bit.vn\themes\blog\layouts\partials\footer.html:12:6": execute of template failed: template: partials/footer.html:12:6: executing "partials/footer.html" at <($.Page.Scratch.Get "include_search") "true">: can't give argument to non-function $.Page.Scratch.Get "include_search"`

I don't understand hugo, but I think there is a problem with this line of code:
`{{ if ($.Page.Scratch.Get "include_search") "true" }}`

Just modify it like this
`{{ if ($.Page.Scratch.Get "include_search")  }}`

Compiled successfully.

I don't know where the problem is.

**Comment by tatthien** [comment]
Hi @lnzx 

Please read more here https://discourse.gohugo.io/t/0-71-1-error-cant-give-argument-to-non-function/25928

I believe that there is something change in v0.72.0

**Comment by tatthien** [comment]
I've already fixed it: https://github.com/12bitvn/12bit.vn/commit/23e30064fb713c495fa83e956af12035459d9cfc
